name: Build Android APK (Python Kivy)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ここが新しいビルドの命令だよ！
      - name: Build with Buildozer
        uses: pypa/buildozer-action@v1
        with:
          save_buildozer_folder: true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: mizu-eye-care-apk
          path: bin/*.apk
